# Generated by Django 5.2.4 on 2025-07-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='link',
            field=models.URLField(max_length=10000),
        ),
    ]
