# Generated by Django 6.0.3 on 2026-03-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sermon_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='link',
        ),
        migrations.AddField(
            model_name='sermon',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
