# Generated by Django 6.0.3 on 2026-03-30 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sermon_link_sermon_youtube_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='sermon',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
