# Generated by Django 6.0.3 on 2026-05-30 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_galleryimage_delete_galleryimages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name_plural": "Galleries"},
        ),
    ]
